name: main

on:
  pull_request:
    branches: [master]

  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@4.0.0
        with:
          node-version: '18'
          cache: 'npm'

      - name: Build project
        run: |
          npm install
          npm run build
